/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RandomRouteImport } from './routes/random'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesGameIdRouteImport } from './routes/games/$gameId'
import { Route as EnSnesGamesRouteImport } from './routes/en.snes-games'
import { Route as EnSegaGenesisGamesRouteImport } from './routes/en.sega-genesis-games'
import { Route as EnPs1GamesRouteImport } from './routes/en.ps1-games'
import { Route as EnNesGamesRouteImport } from './routes/en.nes-games'
import { Route as EnGbaGamesRouteImport } from './routes/en.gba-games'
import { Route as EnArcadeGamesRouteImport } from './routes/en.arcade-games'
import { Route as ApiShareImageRouteImport } from './routes/api/share-image'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as LocaleTermsOfServiceRouteImport } from './routes/$locale.terms-of-service'
import { Route as LocaleRandomRouteImport } from './routes/$locale.random'
import { Route as LocalePrivacyPolicyRouteImport } from './routes/$locale.privacy-policy'
import { Route as LocalePlayMyRomRouteImport } from './routes/$locale.play-my-rom'
import { Route as LocaleLiveRouteImport } from './routes/$locale.live'
import { Route as LocaleBlogRouteImport } from './routes/$locale.blog'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'
import { Route as GamesGameIdPlayRouteImport } from './routes/games/$gameId/play'
import { Route as LocaleGamesGameIdRouteImport } from './routes/$locale.games.$gameId'
import { Route as LocaleBlogBlogIdRouteImport } from './routes/$locale.blog.$blogId'
import { Route as EmbedLocaleGamesGameIdRouteImport } from './routes/embed.$locale.games.$gameId'
import { Route as LocaleGamesGameIdPlayRouteImport } from './routes/$locale.games.$gameId.play'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomRoute = RandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSnesGamesRoute = EnSnesGamesRouteImport.update({
  id: '/en/snes-games',
  path: '/en/snes-games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSegaGenesisGamesRoute = EnSegaGenesisGamesRouteImport.update({
  id: '/en/sega-genesis-games',
  path: '/en/sega-genesis-games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPs1GamesRoute = EnPs1GamesRouteImport.update({
  id: '/en/ps1-games',
  path: '/en/ps1-games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnNesGamesRoute = EnNesGamesRouteImport.update({
  id: '/en/nes-games',
  path: '/en/nes-games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGbaGamesRoute = EnGbaGamesRouteImport.update({
  id: '/en/gba-games',
  path: '/en/gba-games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnArcadeGamesRoute = EnArcadeGamesRouteImport.update({
  id: '/en/arcade-games',
  path: '/en/arcade-games',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareImageRoute = ApiShareImageRouteImport.update({
  id: '/api/share-image',
  path: '/api/share-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleTermsOfServiceRoute = LocaleTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRandomRoute = LocaleRandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyPolicyRoute = LocalePrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePlayMyRomRoute = LocalePlayMyRomRouteImport.update({
  id: '/play-my-rom',
  path: '/play-my-rom',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLiveRoute = LocaleLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogRoute = LocaleBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const GamesGameIdPlayRoute = GamesGameIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => GamesGameIdRoute,
} as any)
const LocaleGamesGameIdRoute = LocaleGamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogBlogIdRoute = LocaleBlogBlogIdRouteImport.update({
  id: '/$blogId',
  path: '/$blogId',
  getParentRoute: () => LocaleBlogRoute,
} as any)
const EmbedLocaleGamesGameIdRoute = EmbedLocaleGamesGameIdRouteImport.update({
  id: '/embed/$locale/games/$gameId',
  path: '/embed/$locale/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleGamesGameIdPlayRoute = LocaleGamesGameIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => LocaleGamesGameIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/random': typeof RandomRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/blog': typeof LocaleBlogRouteWithChildren
  '/$locale/live': typeof LocaleLiveRoute
  '/$locale/play-my-rom': typeof LocalePlayMyRomRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/random': typeof LocaleRandomRoute
  '/$locale/terms-of-service': typeof LocaleTermsOfServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/api/share-image': typeof ApiShareImageRoute
  '/en/arcade-games': typeof EnArcadeGamesRoute
  '/en/gba-games': typeof EnGbaGamesRoute
  '/en/nes-games': typeof EnNesGamesRoute
  '/en/ps1-games': typeof EnPs1GamesRoute
  '/en/sega-genesis-games': typeof EnSegaGenesisGamesRoute
  '/en/snes-games': typeof EnSnesGamesRoute
  '/games/$gameId': typeof GamesGameIdRouteWithChildren
  '/$locale/blog/$blogId': typeof LocaleBlogBlogIdRoute
  '/$locale/games/$gameId': typeof LocaleGamesGameIdRouteWithChildren
  '/games/$gameId/play': typeof GamesGameIdPlayRoute
  '/$locale/games/$gameId/play': typeof LocaleGamesGameIdPlayRoute
  '/embed/$locale/games/$gameId': typeof EmbedLocaleGamesGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/random': typeof RandomRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/blog': typeof LocaleBlogRouteWithChildren
  '/$locale/live': typeof LocaleLiveRoute
  '/$locale/play-my-rom': typeof LocalePlayMyRomRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/random': typeof LocaleRandomRoute
  '/$locale/terms-of-service': typeof LocaleTermsOfServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/api/share-image': typeof ApiShareImageRoute
  '/en/arcade-games': typeof EnArcadeGamesRoute
  '/en/gba-games': typeof EnGbaGamesRoute
  '/en/nes-games': typeof EnNesGamesRoute
  '/en/ps1-games': typeof EnPs1GamesRoute
  '/en/sega-genesis-games': typeof EnSegaGenesisGamesRoute
  '/en/snes-games': typeof EnSnesGamesRoute
  '/games/$gameId': typeof GamesGameIdRouteWithChildren
  '/$locale/blog/$blogId': typeof LocaleBlogBlogIdRoute
  '/$locale/games/$gameId': typeof LocaleGamesGameIdRouteWithChildren
  '/games/$gameId/play': typeof GamesGameIdPlayRoute
  '/$locale/games/$gameId/play': typeof LocaleGamesGameIdPlayRoute
  '/embed/$locale/games/$gameId': typeof EmbedLocaleGamesGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/random': typeof RandomRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/blog': typeof LocaleBlogRouteWithChildren
  '/$locale/live': typeof LocaleLiveRoute
  '/$locale/play-my-rom': typeof LocalePlayMyRomRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/random': typeof LocaleRandomRoute
  '/$locale/terms-of-service': typeof LocaleTermsOfServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/api/share-image': typeof ApiShareImageRoute
  '/en/arcade-games': typeof EnArcadeGamesRoute
  '/en/gba-games': typeof EnGbaGamesRoute
  '/en/nes-games': typeof EnNesGamesRoute
  '/en/ps1-games': typeof EnPs1GamesRoute
  '/en/sega-genesis-games': typeof EnSegaGenesisGamesRoute
  '/en/snes-games': typeof EnSnesGamesRoute
  '/games/$gameId': typeof GamesGameIdRouteWithChildren
  '/$locale/blog/$blogId': typeof LocaleBlogBlogIdRoute
  '/$locale/games/$gameId': typeof LocaleGamesGameIdRouteWithChildren
  '/games/$gameId/play': typeof GamesGameIdPlayRoute
  '/$locale/games/$gameId/play': typeof LocaleGamesGameIdPlayRoute
  '/embed/$locale/games/$gameId': typeof EmbedLocaleGamesGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/manifest.webmanifest'
    | '/random'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/blog'
    | '/$locale/live'
    | '/$locale/play-my-rom'
    | '/$locale/privacy-policy'
    | '/$locale/random'
    | '/$locale/terms-of-service'
    | '/api/health'
    | '/api/share-image'
    | '/en/arcade-games'
    | '/en/gba-games'
    | '/en/nes-games'
    | '/en/ps1-games'
    | '/en/sega-genesis-games'
    | '/en/snes-games'
    | '/games/$gameId'
    | '/$locale/blog/$blogId'
    | '/$locale/games/$gameId'
    | '/games/$gameId/play'
    | '/$locale/games/$gameId/play'
    | '/embed/$locale/games/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/manifest.webmanifest'
    | '/random'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/blog'
    | '/$locale/live'
    | '/$locale/play-my-rom'
    | '/$locale/privacy-policy'
    | '/$locale/random'
    | '/$locale/terms-of-service'
    | '/api/health'
    | '/api/share-image'
    | '/en/arcade-games'
    | '/en/gba-games'
    | '/en/nes-games'
    | '/en/ps1-games'
    | '/en/sega-genesis-games'
    | '/en/snes-games'
    | '/games/$gameId'
    | '/$locale/blog/$blogId'
    | '/$locale/games/$gameId'
    | '/games/$gameId/play'
    | '/$locale/games/$gameId/play'
    | '/embed/$locale/games/$gameId'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/manifest.webmanifest'
    | '/random'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/blog'
    | '/$locale/live'
    | '/$locale/play-my-rom'
    | '/$locale/privacy-policy'
    | '/$locale/random'
    | '/$locale/terms-of-service'
    | '/api/health'
    | '/api/share-image'
    | '/en/arcade-games'
    | '/en/gba-games'
    | '/en/nes-games'
    | '/en/ps1-games'
    | '/en/sega-genesis-games'
    | '/en/snes-games'
    | '/games/$gameId'
    | '/$locale/blog/$blogId'
    | '/$locale/games/$gameId'
    | '/games/$gameId/play'
    | '/$locale/games/$gameId/play'
    | '/embed/$locale/games/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  RandomRoute: typeof RandomRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiShareImageRoute: typeof ApiShareImageRoute
  EnArcadeGamesRoute: typeof EnArcadeGamesRoute
  EnGbaGamesRoute: typeof EnGbaGamesRoute
  EnNesGamesRoute: typeof EnNesGamesRoute
  EnPs1GamesRoute: typeof EnPs1GamesRoute
  EnSegaGenesisGamesRoute: typeof EnSegaGenesisGamesRoute
  EnSnesGamesRoute: typeof EnSnesGamesRoute
  GamesGameIdRoute: typeof GamesGameIdRouteWithChildren
  EmbedLocaleGamesGameIdRoute: typeof EmbedLocaleGamesGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random': {
      id: '/random'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof RandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/snes-games': {
      id: '/en/snes-games'
      path: '/en/snes-games'
      fullPath: '/en/snes-games'
      preLoaderRoute: typeof EnSnesGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/sega-genesis-games': {
      id: '/en/sega-genesis-games'
      path: '/en/sega-genesis-games'
      fullPath: '/en/sega-genesis-games'
      preLoaderRoute: typeof EnSegaGenesisGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/ps1-games': {
      id: '/en/ps1-games'
      path: '/en/ps1-games'
      fullPath: '/en/ps1-games'
      preLoaderRoute: typeof EnPs1GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/nes-games': {
      id: '/en/nes-games'
      path: '/en/nes-games'
      fullPath: '/en/nes-games'
      preLoaderRoute: typeof EnNesGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/gba-games': {
      id: '/en/gba-games'
      path: '/en/gba-games'
      fullPath: '/en/gba-games'
      preLoaderRoute: typeof EnGbaGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/arcade-games': {
      id: '/en/arcade-games'
      path: '/en/arcade-games'
      fullPath: '/en/arcade-games'
      preLoaderRoute: typeof EnArcadeGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share-image': {
      id: '/api/share-image'
      path: '/api/share-image'
      fullPath: '/api/share-image'
      preLoaderRoute: typeof ApiShareImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/terms-of-service': {
      id: '/$locale/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/$locale/terms-of-service'
      preLoaderRoute: typeof LocaleTermsOfServiceRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/random': {
      id: '/$locale/random'
      path: '/random'
      fullPath: '/$locale/random'
      preLoaderRoute: typeof LocaleRandomRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy-policy': {
      id: '/$locale/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/$locale/privacy-policy'
      preLoaderRoute: typeof LocalePrivacyPolicyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/play-my-rom': {
      id: '/$locale/play-my-rom'
      path: '/play-my-rom'
      fullPath: '/$locale/play-my-rom'
      preLoaderRoute: typeof LocalePlayMyRomRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/live': {
      id: '/$locale/live'
      path: '/live'
      fullPath: '/$locale/live'
      preLoaderRoute: typeof LocaleLiveRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog': {
      id: '/$locale/blog'
      path: '/blog'
      fullPath: '/$locale/blog'
      preLoaderRoute: typeof LocaleBlogRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/games/$gameId/play': {
      id: '/games/$gameId/play'
      path: '/play'
      fullPath: '/games/$gameId/play'
      preLoaderRoute: typeof GamesGameIdPlayRouteImport
      parentRoute: typeof GamesGameIdRoute
    }
    '/$locale/games/$gameId': {
      id: '/$locale/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/$locale/games/$gameId'
      preLoaderRoute: typeof LocaleGamesGameIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/$blogId': {
      id: '/$locale/blog/$blogId'
      path: '/$blogId'
      fullPath: '/$locale/blog/$blogId'
      preLoaderRoute: typeof LocaleBlogBlogIdRouteImport
      parentRoute: typeof LocaleBlogRoute
    }
    '/embed/$locale/games/$gameId': {
      id: '/embed/$locale/games/$gameId'
      path: '/embed/$locale/games/$gameId'
      fullPath: '/embed/$locale/games/$gameId'
      preLoaderRoute: typeof EmbedLocaleGamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/games/$gameId/play': {
      id: '/$locale/games/$gameId/play'
      path: '/play'
      fullPath: '/$locale/games/$gameId/play'
      preLoaderRoute: typeof LocaleGamesGameIdPlayRouteImport
      parentRoute: typeof LocaleGamesGameIdRoute
    }
  }
}

interface LocaleBlogRouteChildren {
  LocaleBlogBlogIdRoute: typeof LocaleBlogBlogIdRoute
}

const LocaleBlogRouteChildren: LocaleBlogRouteChildren = {
  LocaleBlogBlogIdRoute: LocaleBlogBlogIdRoute,
}

const LocaleBlogRouteWithChildren = LocaleBlogRoute._addFileChildren(
  LocaleBlogRouteChildren,
)

interface LocaleGamesGameIdRouteChildren {
  LocaleGamesGameIdPlayRoute: typeof LocaleGamesGameIdPlayRoute
}

const LocaleGamesGameIdRouteChildren: LocaleGamesGameIdRouteChildren = {
  LocaleGamesGameIdPlayRoute: LocaleGamesGameIdPlayRoute,
}

const LocaleGamesGameIdRouteWithChildren =
  LocaleGamesGameIdRoute._addFileChildren(LocaleGamesGameIdRouteChildren)

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleBlogRoute: typeof LocaleBlogRouteWithChildren
  LocaleLiveRoute: typeof LocaleLiveRoute
  LocalePlayMyRomRoute: typeof LocalePlayMyRomRoute
  LocalePrivacyPolicyRoute: typeof LocalePrivacyPolicyRoute
  LocaleRandomRoute: typeof LocaleRandomRoute
  LocaleTermsOfServiceRoute: typeof LocaleTermsOfServiceRoute
  LocaleGamesGameIdRoute: typeof LocaleGamesGameIdRouteWithChildren
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleBlogRoute: LocaleBlogRouteWithChildren,
  LocaleLiveRoute: LocaleLiveRoute,
  LocalePlayMyRomRoute: LocalePlayMyRomRoute,
  LocalePrivacyPolicyRoute: LocalePrivacyPolicyRoute,
  LocaleRandomRoute: LocaleRandomRoute,
  LocaleTermsOfServiceRoute: LocaleTermsOfServiceRoute,
  LocaleGamesGameIdRoute: LocaleGamesGameIdRouteWithChildren,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface GamesGameIdRouteChildren {
  GamesGameIdPlayRoute: typeof GamesGameIdPlayRoute
}

const GamesGameIdRouteChildren: GamesGameIdRouteChildren = {
  GamesGameIdPlayRoute: GamesGameIdPlayRoute,
}

const GamesGameIdRouteWithChildren = GamesGameIdRoute._addFileChildren(
  GamesGameIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  RandomRoute: RandomRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiShareImageRoute: ApiShareImageRoute,
  EnArcadeGamesRoute: EnArcadeGamesRoute,
  EnGbaGamesRoute: EnGbaGamesRoute,
  EnNesGamesRoute: EnNesGamesRoute,
  EnPs1GamesRoute: EnPs1GamesRoute,
  EnSegaGenesisGamesRoute: EnSegaGenesisGamesRoute,
  EnSnesGamesRoute: EnSnesGamesRoute,
  GamesGameIdRoute: GamesGameIdRouteWithChildren,
  EmbedLocaleGamesGameIdRoute: EmbedLocaleGamesGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
