/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopIdleGamesRouteImport } from './routes/top-idle-games'
import { Route as SportsGamesRouteImport } from './routes/sports-games'
import { Route as SnesGamesRouteImport } from './routes/snes-games'
import { Route as SnesRouteImport } from './routes/snes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SegaGenesisGamesRouteImport } from './routes/sega-genesis-games'
import { Route as SegaGenesisRouteImport } from './routes/sega-genesis'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RandomRouteImport } from './routes/random'
import { Route as RacingGamesRouteImport } from './routes/racing-games'
import { Route as PuzzleGamesRouteImport } from './routes/puzzle-games'
import { Route as Ps1GamesRouteImport } from './routes/ps1-games'
import { Route as Ps1RouteImport } from './routes/ps1'
import { Route as PlaystationGamesRouteImport } from './routes/playstation-games'
import { Route as NesGamesRouteImport } from './routes/nes-games'
import { Route as NesRouteImport } from './routes/nes'
import { Route as N64GamesRouteImport } from './routes/n64-games'
import { Route as N64RouteImport } from './routes/n64'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as GbaGamesRouteImport } from './routes/gba-games'
import { Route as GbaRouteImport } from './routes/gba'
import { Route as FunQuizDothtmlRouteImport } from './routes/fun-quiz[.]html'
import { Route as FunQuizRouteImport } from './routes/fun-quiz'
import { Route as BestUnblockedGamesRouteImport } from './routes/best-unblocked-games'
import { Route as ArcadeGamesRouteImport } from './routes/arcade-games'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayGameIdRouteImport } from './routes/play.$gameId'
import { Route as GamesGameIdRouteImport } from './routes/games/$gameId'
import { Route as EnSnesGamesRouteImport } from './routes/en.snes-games'
import { Route as EnSnesRouteImport } from './routes/en.snes'
import { Route as EnSegaGenesisGamesRouteImport } from './routes/en.sega-genesis-games'
import { Route as EnSegaGenesisRouteImport } from './routes/en.sega-genesis'
import { Route as EnPs1GamesRouteImport } from './routes/en.ps1-games'
import { Route as EnPs1RouteImport } from './routes/en.ps1'
import { Route as EnPlaystationGamesRouteImport } from './routes/en.playstation-games'
import { Route as EnNesGamesRouteImport } from './routes/en.nes-games'
import { Route as EnNesRouteImport } from './routes/en.nes'
import { Route as EnN64GamesRouteImport } from './routes/en.n64-games'
import { Route as EnGenesisGamesRouteImport } from './routes/en.genesis-games'
import { Route as EnGbaGamesRouteImport } from './routes/en.gba-games'
import { Route as EnGbaRouteImport } from './routes/en.gba'
import { Route as EnArcadeGamesRouteImport } from './routes/en.arcade-games'
import { Route as EnArcadeRouteImport } from './routes/en.arcade'
import { Route as BlogBlogIdRouteImport } from './routes/blog.$blogId'
import { Route as ArticlesHowToPlayGamesOnlineWithoutDownloadingRouteImport } from './routes/articles.how-to-play-games-online-without-downloading'
import { Route as ArticlesArticleIdRouteImport } from './routes/articles.$articleId'
import { Route as ApiShareImageRouteImport } from './routes/api/share-image'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as LocaleTermsOfServiceRouteImport } from './routes/$locale.terms-of-service'
import { Route as LocaleRandomRouteImport } from './routes/$locale.random'
import { Route as LocalePrivacyPolicyRouteImport } from './routes/$locale.privacy-policy'
import { Route as LocalePlayMyRomRouteImport } from './routes/$locale.play-my-rom'
import { Route as LocaleLiveRouteImport } from './routes/$locale.live'
import { Route as LocaleBlogRouteImport } from './routes/$locale.blog'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'
import { Route as LibraryGenresGenreRouteImport } from './routes/library.genres.$genre'
import { Route as GamesGameIdPlayRouteImport } from './routes/games/$gameId/play'
import { Route as LocaleGamesGameIdRouteImport } from './routes/$locale.games.$gameId'
import { Route as LocaleBlogBlogIdRouteImport } from './routes/$locale.blog.$blogId'
import { Route as EmbedLocaleGamesGameIdRouteImport } from './routes/embed.$locale.games.$gameId'
import { Route as LocaleGamesGameIdPlayRouteImport } from './routes/$locale.games.$gameId.play'

const TopIdleGamesRoute = TopIdleGamesRouteImport.update({
  id: '/top-idle-games',
  path: '/top-idle-games',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsGamesRoute = SportsGamesRouteImport.update({
  id: '/sports-games',
  path: '/sports-games',
  getParentRoute: () => rootRouteImport,
} as any)
const SnesGamesRoute = SnesGamesRouteImport.update({
  id: '/snes-games',
  path: '/snes-games',
  getParentRoute: () => rootRouteImport,
} as any)
const SnesRoute = SnesRouteImport.update({
  id: '/snes',
  path: '/snes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SegaGenesisGamesRoute = SegaGenesisGamesRouteImport.update({
  id: '/sega-genesis-games',
  path: '/sega-genesis-games',
  getParentRoute: () => rootRouteImport,
} as any)
const SegaGenesisRoute = SegaGenesisRouteImport.update({
  id: '/sega-genesis',
  path: '/sega-genesis',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomRoute = RandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => rootRouteImport,
} as any)
const RacingGamesRoute = RacingGamesRouteImport.update({
  id: '/racing-games',
  path: '/racing-games',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzleGamesRoute = PuzzleGamesRouteImport.update({
  id: '/puzzle-games',
  path: '/puzzle-games',
  getParentRoute: () => rootRouteImport,
} as any)
const Ps1GamesRoute = Ps1GamesRouteImport.update({
  id: '/ps1-games',
  path: '/ps1-games',
  getParentRoute: () => rootRouteImport,
} as any)
const Ps1Route = Ps1RouteImport.update({
  id: '/ps1',
  path: '/ps1',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaystationGamesRoute = PlaystationGamesRouteImport.update({
  id: '/playstation-games',
  path: '/playstation-games',
  getParentRoute: () => rootRouteImport,
} as any)
const NesGamesRoute = NesGamesRouteImport.update({
  id: '/nes-games',
  path: '/nes-games',
  getParentRoute: () => rootRouteImport,
} as any)
const NesRoute = NesRouteImport.update({
  id: '/nes',
  path: '/nes',
  getParentRoute: () => rootRouteImport,
} as any)
const N64GamesRoute = N64GamesRouteImport.update({
  id: '/n64-games',
  path: '/n64-games',
  getParentRoute: () => rootRouteImport,
} as any)
const N64Route = N64RouteImport.update({
  id: '/n64',
  path: '/n64',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const GbaGamesRoute = GbaGamesRouteImport.update({
  id: '/gba-games',
  path: '/gba-games',
  getParentRoute: () => rootRouteImport,
} as any)
const GbaRoute = GbaRouteImport.update({
  id: '/gba',
  path: '/gba',
  getParentRoute: () => rootRouteImport,
} as any)
const FunQuizDothtmlRoute = FunQuizDothtmlRouteImport.update({
  id: '/fun-quiz.html',
  path: '/fun-quiz.html',
  getParentRoute: () => rootRouteImport,
} as any)
const FunQuizRoute = FunQuizRouteImport.update({
  id: '/fun-quiz',
  path: '/fun-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const BestUnblockedGamesRoute = BestUnblockedGamesRouteImport.update({
  id: '/best-unblocked-games',
  path: '/best-unblocked-games',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeGamesRoute = ArcadeGamesRouteImport.update({
  id: '/arcade-games',
  path: '/arcade-games',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameIdRoute = PlayGameIdRouteImport.update({
  id: '/play/$gameId',
  path: '/play/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSnesGamesRoute = EnSnesGamesRouteImport.update({
  id: '/en/snes-games',
  path: '/en/snes-games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSnesRoute = EnSnesRouteImport.update({
  id: '/en/snes',
  path: '/en/snes',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSegaGenesisGamesRoute = EnSegaGenesisGamesRouteImport.update({
  id: '/en/sega-genesis-games',
  path: '/en/sega-genesis-games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSegaGenesisRoute = EnSegaGenesisRouteImport.update({
  id: '/en/sega-genesis',
  path: '/en/sega-genesis',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPs1GamesRoute = EnPs1GamesRouteImport.update({
  id: '/en/ps1-games',
  path: '/en/ps1-games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPs1Route = EnPs1RouteImport.update({
  id: '/en/ps1',
  path: '/en/ps1',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPlaystationGamesRoute = EnPlaystationGamesRouteImport.update({
  id: '/en/playstation-games',
  path: '/en/playstation-games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnNesGamesRoute = EnNesGamesRouteImport.update({
  id: '/en/nes-games',
  path: '/en/nes-games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnNesRoute = EnNesRouteImport.update({
  id: '/en/nes',
  path: '/en/nes',
  getParentRoute: () => rootRouteImport,
} as any)
const EnN64GamesRoute = EnN64GamesRouteImport.update({
  id: '/en/n64-games',
  path: '/en/n64-games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGenesisGamesRoute = EnGenesisGamesRouteImport.update({
  id: '/en/genesis-games',
  path: '/en/genesis-games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGbaGamesRoute = EnGbaGamesRouteImport.update({
  id: '/en/gba-games',
  path: '/en/gba-games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGbaRoute = EnGbaRouteImport.update({
  id: '/en/gba',
  path: '/en/gba',
  getParentRoute: () => rootRouteImport,
} as any)
const EnArcadeGamesRoute = EnArcadeGamesRouteImport.update({
  id: '/en/arcade-games',
  path: '/en/arcade-games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnArcadeRoute = EnArcadeRouteImport.update({
  id: '/en/arcade',
  path: '/en/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBlogIdRoute = BlogBlogIdRouteImport.update({
  id: '/blog/$blogId',
  path: '/blog/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesHowToPlayGamesOnlineWithoutDownloadingRoute =
  ArticlesHowToPlayGamesOnlineWithoutDownloadingRouteImport.update({
    id: '/articles/how-to-play-games-online-without-downloading',
    path: '/articles/how-to-play-games-online-without-downloading',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticlesArticleIdRoute = ArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareImageRoute = ApiShareImageRouteImport.update({
  id: '/api/share-image',
  path: '/api/share-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleTermsOfServiceRoute = LocaleTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRandomRoute = LocaleRandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyPolicyRoute = LocalePrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePlayMyRomRoute = LocalePlayMyRomRouteImport.update({
  id: '/play-my-rom',
  path: '/play-my-rom',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLiveRoute = LocaleLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogRoute = LocaleBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LibraryGenresGenreRoute = LibraryGenresGenreRouteImport.update({
  id: '/library/genres/$genre',
  path: '/library/genres/$genre',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdPlayRoute = GamesGameIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => GamesGameIdRoute,
} as any)
const LocaleGamesGameIdRoute = LocaleGamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogBlogIdRoute = LocaleBlogBlogIdRouteImport.update({
  id: '/$blogId',
  path: '/$blogId',
  getParentRoute: () => LocaleBlogRoute,
} as any)
const EmbedLocaleGamesGameIdRoute = EmbedLocaleGamesGameIdRouteImport.update({
  id: '/embed/$locale/games/$gameId',
  path: '/embed/$locale/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleGamesGameIdPlayRoute = LocaleGamesGameIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => LocaleGamesGameIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/arcade': typeof ArcadeRoute
  '/arcade-games': typeof ArcadeGamesRoute
  '/best-unblocked-games': typeof BestUnblockedGamesRoute
  '/fun-quiz': typeof FunQuizRoute
  '/fun-quiz.html': typeof FunQuizDothtmlRoute
  '/gba': typeof GbaRoute
  '/gba-games': typeof GbaGamesRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/n64': typeof N64Route
  '/n64-games': typeof N64GamesRoute
  '/nes': typeof NesRoute
  '/nes-games': typeof NesGamesRoute
  '/playstation-games': typeof PlaystationGamesRoute
  '/ps1': typeof Ps1Route
  '/ps1-games': typeof Ps1GamesRoute
  '/puzzle-games': typeof PuzzleGamesRoute
  '/racing-games': typeof RacingGamesRoute
  '/random': typeof RandomRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sega-genesis': typeof SegaGenesisRoute
  '/sega-genesis-games': typeof SegaGenesisGamesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snes': typeof SnesRoute
  '/snes-games': typeof SnesGamesRoute
  '/sports-games': typeof SportsGamesRoute
  '/top-idle-games': typeof TopIdleGamesRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/blog': typeof LocaleBlogRouteWithChildren
  '/$locale/live': typeof LocaleLiveRoute
  '/$locale/play-my-rom': typeof LocalePlayMyRomRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/random': typeof LocaleRandomRoute
  '/$locale/terms-of-service': typeof LocaleTermsOfServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/api/share-image': typeof ApiShareImageRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/articles/how-to-play-games-online-without-downloading': typeof ArticlesHowToPlayGamesOnlineWithoutDownloadingRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/en/arcade': typeof EnArcadeRoute
  '/en/arcade-games': typeof EnArcadeGamesRoute
  '/en/gba': typeof EnGbaRoute
  '/en/gba-games': typeof EnGbaGamesRoute
  '/en/genesis-games': typeof EnGenesisGamesRoute
  '/en/n64-games': typeof EnN64GamesRoute
  '/en/nes': typeof EnNesRoute
  '/en/nes-games': typeof EnNesGamesRoute
  '/en/playstation-games': typeof EnPlaystationGamesRoute
  '/en/ps1': typeof EnPs1Route
  '/en/ps1-games': typeof EnPs1GamesRoute
  '/en/sega-genesis': typeof EnSegaGenesisRoute
  '/en/sega-genesis-games': typeof EnSegaGenesisGamesRoute
  '/en/snes': typeof EnSnesRoute
  '/en/snes-games': typeof EnSnesGamesRoute
  '/games/$gameId': typeof GamesGameIdRouteWithChildren
  '/play/$gameId': typeof PlayGameIdRoute
  '/$locale/blog/$blogId': typeof LocaleBlogBlogIdRoute
  '/$locale/games/$gameId': typeof LocaleGamesGameIdRouteWithChildren
  '/games/$gameId/play': typeof GamesGameIdPlayRoute
  '/library/genres/$genre': typeof LibraryGenresGenreRoute
  '/$locale/games/$gameId/play': typeof LocaleGamesGameIdPlayRoute
  '/embed/$locale/games/$gameId': typeof EmbedLocaleGamesGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/arcade': typeof ArcadeRoute
  '/arcade-games': typeof ArcadeGamesRoute
  '/best-unblocked-games': typeof BestUnblockedGamesRoute
  '/fun-quiz': typeof FunQuizRoute
  '/fun-quiz.html': typeof FunQuizDothtmlRoute
  '/gba': typeof GbaRoute
  '/gba-games': typeof GbaGamesRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/n64': typeof N64Route
  '/n64-games': typeof N64GamesRoute
  '/nes': typeof NesRoute
  '/nes-games': typeof NesGamesRoute
  '/playstation-games': typeof PlaystationGamesRoute
  '/ps1': typeof Ps1Route
  '/ps1-games': typeof Ps1GamesRoute
  '/puzzle-games': typeof PuzzleGamesRoute
  '/racing-games': typeof RacingGamesRoute
  '/random': typeof RandomRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sega-genesis': typeof SegaGenesisRoute
  '/sega-genesis-games': typeof SegaGenesisGamesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snes': typeof SnesRoute
  '/snes-games': typeof SnesGamesRoute
  '/sports-games': typeof SportsGamesRoute
  '/top-idle-games': typeof TopIdleGamesRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/blog': typeof LocaleBlogRouteWithChildren
  '/$locale/live': typeof LocaleLiveRoute
  '/$locale/play-my-rom': typeof LocalePlayMyRomRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/random': typeof LocaleRandomRoute
  '/$locale/terms-of-service': typeof LocaleTermsOfServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/api/share-image': typeof ApiShareImageRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/articles/how-to-play-games-online-without-downloading': typeof ArticlesHowToPlayGamesOnlineWithoutDownloadingRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/en/arcade': typeof EnArcadeRoute
  '/en/arcade-games': typeof EnArcadeGamesRoute
  '/en/gba': typeof EnGbaRoute
  '/en/gba-games': typeof EnGbaGamesRoute
  '/en/genesis-games': typeof EnGenesisGamesRoute
  '/en/n64-games': typeof EnN64GamesRoute
  '/en/nes': typeof EnNesRoute
  '/en/nes-games': typeof EnNesGamesRoute
  '/en/playstation-games': typeof EnPlaystationGamesRoute
  '/en/ps1': typeof EnPs1Route
  '/en/ps1-games': typeof EnPs1GamesRoute
  '/en/sega-genesis': typeof EnSegaGenesisRoute
  '/en/sega-genesis-games': typeof EnSegaGenesisGamesRoute
  '/en/snes': typeof EnSnesRoute
  '/en/snes-games': typeof EnSnesGamesRoute
  '/games/$gameId': typeof GamesGameIdRouteWithChildren
  '/play/$gameId': typeof PlayGameIdRoute
  '/$locale/blog/$blogId': typeof LocaleBlogBlogIdRoute
  '/$locale/games/$gameId': typeof LocaleGamesGameIdRouteWithChildren
  '/games/$gameId/play': typeof GamesGameIdPlayRoute
  '/library/genres/$genre': typeof LibraryGenresGenreRoute
  '/$locale/games/$gameId/play': typeof LocaleGamesGameIdPlayRoute
  '/embed/$locale/games/$gameId': typeof EmbedLocaleGamesGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/arcade': typeof ArcadeRoute
  '/arcade-games': typeof ArcadeGamesRoute
  '/best-unblocked-games': typeof BestUnblockedGamesRoute
  '/fun-quiz': typeof FunQuizRoute
  '/fun-quiz.html': typeof FunQuizDothtmlRoute
  '/gba': typeof GbaRoute
  '/gba-games': typeof GbaGamesRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/n64': typeof N64Route
  '/n64-games': typeof N64GamesRoute
  '/nes': typeof NesRoute
  '/nes-games': typeof NesGamesRoute
  '/playstation-games': typeof PlaystationGamesRoute
  '/ps1': typeof Ps1Route
  '/ps1-games': typeof Ps1GamesRoute
  '/puzzle-games': typeof PuzzleGamesRoute
  '/racing-games': typeof RacingGamesRoute
  '/random': typeof RandomRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sega-genesis': typeof SegaGenesisRoute
  '/sega-genesis-games': typeof SegaGenesisGamesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snes': typeof SnesRoute
  '/snes-games': typeof SnesGamesRoute
  '/sports-games': typeof SportsGamesRoute
  '/top-idle-games': typeof TopIdleGamesRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/blog': typeof LocaleBlogRouteWithChildren
  '/$locale/live': typeof LocaleLiveRoute
  '/$locale/play-my-rom': typeof LocalePlayMyRomRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/random': typeof LocaleRandomRoute
  '/$locale/terms-of-service': typeof LocaleTermsOfServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/api/share-image': typeof ApiShareImageRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/articles/how-to-play-games-online-without-downloading': typeof ArticlesHowToPlayGamesOnlineWithoutDownloadingRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/en/arcade': typeof EnArcadeRoute
  '/en/arcade-games': typeof EnArcadeGamesRoute
  '/en/gba': typeof EnGbaRoute
  '/en/gba-games': typeof EnGbaGamesRoute
  '/en/genesis-games': typeof EnGenesisGamesRoute
  '/en/n64-games': typeof EnN64GamesRoute
  '/en/nes': typeof EnNesRoute
  '/en/nes-games': typeof EnNesGamesRoute
  '/en/playstation-games': typeof EnPlaystationGamesRoute
  '/en/ps1': typeof EnPs1Route
  '/en/ps1-games': typeof EnPs1GamesRoute
  '/en/sega-genesis': typeof EnSegaGenesisRoute
  '/en/sega-genesis-games': typeof EnSegaGenesisGamesRoute
  '/en/snes': typeof EnSnesRoute
  '/en/snes-games': typeof EnSnesGamesRoute
  '/games/$gameId': typeof GamesGameIdRouteWithChildren
  '/play/$gameId': typeof PlayGameIdRoute
  '/$locale/blog/$blogId': typeof LocaleBlogBlogIdRoute
  '/$locale/games/$gameId': typeof LocaleGamesGameIdRouteWithChildren
  '/games/$gameId/play': typeof GamesGameIdPlayRoute
  '/library/genres/$genre': typeof LibraryGenresGenreRoute
  '/$locale/games/$gameId/play': typeof LocaleGamesGameIdPlayRoute
  '/embed/$locale/games/$gameId': typeof EmbedLocaleGamesGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/arcade'
    | '/arcade-games'
    | '/best-unblocked-games'
    | '/fun-quiz'
    | '/fun-quiz.html'
    | '/gba'
    | '/gba-games'
    | '/manifest.webmanifest'
    | '/n64'
    | '/n64-games'
    | '/nes'
    | '/nes-games'
    | '/playstation-games'
    | '/ps1'
    | '/ps1-games'
    | '/puzzle-games'
    | '/racing-games'
    | '/random'
    | '/robots.txt'
    | '/sega-genesis'
    | '/sega-genesis-games'
    | '/sitemap.xml'
    | '/snes'
    | '/snes-games'
    | '/sports-games'
    | '/top-idle-games'
    | '/$locale/about'
    | '/$locale/blog'
    | '/$locale/live'
    | '/$locale/play-my-rom'
    | '/$locale/privacy-policy'
    | '/$locale/random'
    | '/$locale/terms-of-service'
    | '/api/health'
    | '/api/share-image'
    | '/articles/$articleId'
    | '/articles/how-to-play-games-online-without-downloading'
    | '/blog/$blogId'
    | '/en/arcade'
    | '/en/arcade-games'
    | '/en/gba'
    | '/en/gba-games'
    | '/en/genesis-games'
    | '/en/n64-games'
    | '/en/nes'
    | '/en/nes-games'
    | '/en/playstation-games'
    | '/en/ps1'
    | '/en/ps1-games'
    | '/en/sega-genesis'
    | '/en/sega-genesis-games'
    | '/en/snes'
    | '/en/snes-games'
    | '/games/$gameId'
    | '/play/$gameId'
    | '/$locale/blog/$blogId'
    | '/$locale/games/$gameId'
    | '/games/$gameId/play'
    | '/library/genres/$genre'
    | '/$locale/games/$gameId/play'
    | '/embed/$locale/games/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/arcade'
    | '/arcade-games'
    | '/best-unblocked-games'
    | '/fun-quiz'
    | '/fun-quiz.html'
    | '/gba'
    | '/gba-games'
    | '/manifest.webmanifest'
    | '/n64'
    | '/n64-games'
    | '/nes'
    | '/nes-games'
    | '/playstation-games'
    | '/ps1'
    | '/ps1-games'
    | '/puzzle-games'
    | '/racing-games'
    | '/random'
    | '/robots.txt'
    | '/sega-genesis'
    | '/sega-genesis-games'
    | '/sitemap.xml'
    | '/snes'
    | '/snes-games'
    | '/sports-games'
    | '/top-idle-games'
    | '/$locale/about'
    | '/$locale/blog'
    | '/$locale/live'
    | '/$locale/play-my-rom'
    | '/$locale/privacy-policy'
    | '/$locale/random'
    | '/$locale/terms-of-service'
    | '/api/health'
    | '/api/share-image'
    | '/articles/$articleId'
    | '/articles/how-to-play-games-online-without-downloading'
    | '/blog/$blogId'
    | '/en/arcade'
    | '/en/arcade-games'
    | '/en/gba'
    | '/en/gba-games'
    | '/en/genesis-games'
    | '/en/n64-games'
    | '/en/nes'
    | '/en/nes-games'
    | '/en/playstation-games'
    | '/en/ps1'
    | '/en/ps1-games'
    | '/en/sega-genesis'
    | '/en/sega-genesis-games'
    | '/en/snes'
    | '/en/snes-games'
    | '/games/$gameId'
    | '/play/$gameId'
    | '/$locale/blog/$blogId'
    | '/$locale/games/$gameId'
    | '/games/$gameId/play'
    | '/library/genres/$genre'
    | '/$locale/games/$gameId/play'
    | '/embed/$locale/games/$gameId'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/arcade'
    | '/arcade-games'
    | '/best-unblocked-games'
    | '/fun-quiz'
    | '/fun-quiz.html'
    | '/gba'
    | '/gba-games'
    | '/manifest.webmanifest'
    | '/n64'
    | '/n64-games'
    | '/nes'
    | '/nes-games'
    | '/playstation-games'
    | '/ps1'
    | '/ps1-games'
    | '/puzzle-games'
    | '/racing-games'
    | '/random'
    | '/robots.txt'
    | '/sega-genesis'
    | '/sega-genesis-games'
    | '/sitemap.xml'
    | '/snes'
    | '/snes-games'
    | '/sports-games'
    | '/top-idle-games'
    | '/$locale/about'
    | '/$locale/blog'
    | '/$locale/live'
    | '/$locale/play-my-rom'
    | '/$locale/privacy-policy'
    | '/$locale/random'
    | '/$locale/terms-of-service'
    | '/api/health'
    | '/api/share-image'
    | '/articles/$articleId'
    | '/articles/how-to-play-games-online-without-downloading'
    | '/blog/$blogId'
    | '/en/arcade'
    | '/en/arcade-games'
    | '/en/gba'
    | '/en/gba-games'
    | '/en/genesis-games'
    | '/en/n64-games'
    | '/en/nes'
    | '/en/nes-games'
    | '/en/playstation-games'
    | '/en/ps1'
    | '/en/ps1-games'
    | '/en/sega-genesis'
    | '/en/sega-genesis-games'
    | '/en/snes'
    | '/en/snes-games'
    | '/games/$gameId'
    | '/play/$gameId'
    | '/$locale/blog/$blogId'
    | '/$locale/games/$gameId'
    | '/games/$gameId/play'
    | '/library/genres/$genre'
    | '/$locale/games/$gameId/play'
    | '/embed/$locale/games/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  ArcadeRoute: typeof ArcadeRoute
  ArcadeGamesRoute: typeof ArcadeGamesRoute
  BestUnblockedGamesRoute: typeof BestUnblockedGamesRoute
  FunQuizRoute: typeof FunQuizRoute
  FunQuizDothtmlRoute: typeof FunQuizDothtmlRoute
  GbaRoute: typeof GbaRoute
  GbaGamesRoute: typeof GbaGamesRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  N64Route: typeof N64Route
  N64GamesRoute: typeof N64GamesRoute
  NesRoute: typeof NesRoute
  NesGamesRoute: typeof NesGamesRoute
  PlaystationGamesRoute: typeof PlaystationGamesRoute
  Ps1Route: typeof Ps1Route
  Ps1GamesRoute: typeof Ps1GamesRoute
  PuzzleGamesRoute: typeof PuzzleGamesRoute
  RacingGamesRoute: typeof RacingGamesRoute
  RandomRoute: typeof RandomRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SegaGenesisRoute: typeof SegaGenesisRoute
  SegaGenesisGamesRoute: typeof SegaGenesisGamesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SnesRoute: typeof SnesRoute
  SnesGamesRoute: typeof SnesGamesRoute
  SportsGamesRoute: typeof SportsGamesRoute
  TopIdleGamesRoute: typeof TopIdleGamesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiShareImageRoute: typeof ApiShareImageRoute
  ArticlesArticleIdRoute: typeof ArticlesArticleIdRoute
  ArticlesHowToPlayGamesOnlineWithoutDownloadingRoute: typeof ArticlesHowToPlayGamesOnlineWithoutDownloadingRoute
  BlogBlogIdRoute: typeof BlogBlogIdRoute
  EnArcadeRoute: typeof EnArcadeRoute
  EnArcadeGamesRoute: typeof EnArcadeGamesRoute
  EnGbaRoute: typeof EnGbaRoute
  EnGbaGamesRoute: typeof EnGbaGamesRoute
  EnGenesisGamesRoute: typeof EnGenesisGamesRoute
  EnN64GamesRoute: typeof EnN64GamesRoute
  EnNesRoute: typeof EnNesRoute
  EnNesGamesRoute: typeof EnNesGamesRoute
  EnPlaystationGamesRoute: typeof EnPlaystationGamesRoute
  EnPs1Route: typeof EnPs1Route
  EnPs1GamesRoute: typeof EnPs1GamesRoute
  EnSegaGenesisRoute: typeof EnSegaGenesisRoute
  EnSegaGenesisGamesRoute: typeof EnSegaGenesisGamesRoute
  EnSnesRoute: typeof EnSnesRoute
  EnSnesGamesRoute: typeof EnSnesGamesRoute
  GamesGameIdRoute: typeof GamesGameIdRouteWithChildren
  PlayGameIdRoute: typeof PlayGameIdRoute
  LibraryGenresGenreRoute: typeof LibraryGenresGenreRoute
  EmbedLocaleGamesGameIdRoute: typeof EmbedLocaleGamesGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/top-idle-games': {
      id: '/top-idle-games'
      path: '/top-idle-games'
      fullPath: '/top-idle-games'
      preLoaderRoute: typeof TopIdleGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-games': {
      id: '/sports-games'
      path: '/sports-games'
      fullPath: '/sports-games'
      preLoaderRoute: typeof SportsGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snes-games': {
      id: '/snes-games'
      path: '/snes-games'
      fullPath: '/snes-games'
      preLoaderRoute: typeof SnesGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snes': {
      id: '/snes'
      path: '/snes'
      fullPath: '/snes'
      preLoaderRoute: typeof SnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sega-genesis-games': {
      id: '/sega-genesis-games'
      path: '/sega-genesis-games'
      fullPath: '/sega-genesis-games'
      preLoaderRoute: typeof SegaGenesisGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sega-genesis': {
      id: '/sega-genesis'
      path: '/sega-genesis'
      fullPath: '/sega-genesis'
      preLoaderRoute: typeof SegaGenesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random': {
      id: '/random'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof RandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/racing-games': {
      id: '/racing-games'
      path: '/racing-games'
      fullPath: '/racing-games'
      preLoaderRoute: typeof RacingGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzle-games': {
      id: '/puzzle-games'
      path: '/puzzle-games'
      fullPath: '/puzzle-games'
      preLoaderRoute: typeof PuzzleGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ps1-games': {
      id: '/ps1-games'
      path: '/ps1-games'
      fullPath: '/ps1-games'
      preLoaderRoute: typeof Ps1GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ps1': {
      id: '/ps1'
      path: '/ps1'
      fullPath: '/ps1'
      preLoaderRoute: typeof Ps1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playstation-games': {
      id: '/playstation-games'
      path: '/playstation-games'
      fullPath: '/playstation-games'
      preLoaderRoute: typeof PlaystationGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nes-games': {
      id: '/nes-games'
      path: '/nes-games'
      fullPath: '/nes-games'
      preLoaderRoute: typeof NesGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nes': {
      id: '/nes'
      path: '/nes'
      fullPath: '/nes'
      preLoaderRoute: typeof NesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n64-games': {
      id: '/n64-games'
      path: '/n64-games'
      fullPath: '/n64-games'
      preLoaderRoute: typeof N64GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n64': {
      id: '/n64'
      path: '/n64'
      fullPath: '/n64'
      preLoaderRoute: typeof N64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gba-games': {
      id: '/gba-games'
      path: '/gba-games'
      fullPath: '/gba-games'
      preLoaderRoute: typeof GbaGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gba': {
      id: '/gba'
      path: '/gba'
      fullPath: '/gba'
      preLoaderRoute: typeof GbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fun-quiz.html': {
      id: '/fun-quiz.html'
      path: '/fun-quiz.html'
      fullPath: '/fun-quiz.html'
      preLoaderRoute: typeof FunQuizDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fun-quiz': {
      id: '/fun-quiz'
      path: '/fun-quiz'
      fullPath: '/fun-quiz'
      preLoaderRoute: typeof FunQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-unblocked-games': {
      id: '/best-unblocked-games'
      path: '/best-unblocked-games'
      fullPath: '/best-unblocked-games'
      preLoaderRoute: typeof BestUnblockedGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade-games': {
      id: '/arcade-games'
      path: '/arcade-games'
      fullPath: '/arcade-games'
      preLoaderRoute: typeof ArcadeGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$gameId': {
      id: '/play/$gameId'
      path: '/play/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof PlayGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/snes-games': {
      id: '/en/snes-games'
      path: '/en/snes-games'
      fullPath: '/en/snes-games'
      preLoaderRoute: typeof EnSnesGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/snes': {
      id: '/en/snes'
      path: '/en/snes'
      fullPath: '/en/snes'
      preLoaderRoute: typeof EnSnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/sega-genesis-games': {
      id: '/en/sega-genesis-games'
      path: '/en/sega-genesis-games'
      fullPath: '/en/sega-genesis-games'
      preLoaderRoute: typeof EnSegaGenesisGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/sega-genesis': {
      id: '/en/sega-genesis'
      path: '/en/sega-genesis'
      fullPath: '/en/sega-genesis'
      preLoaderRoute: typeof EnSegaGenesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/ps1-games': {
      id: '/en/ps1-games'
      path: '/en/ps1-games'
      fullPath: '/en/ps1-games'
      preLoaderRoute: typeof EnPs1GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/ps1': {
      id: '/en/ps1'
      path: '/en/ps1'
      fullPath: '/en/ps1'
      preLoaderRoute: typeof EnPs1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/playstation-games': {
      id: '/en/playstation-games'
      path: '/en/playstation-games'
      fullPath: '/en/playstation-games'
      preLoaderRoute: typeof EnPlaystationGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/nes-games': {
      id: '/en/nes-games'
      path: '/en/nes-games'
      fullPath: '/en/nes-games'
      preLoaderRoute: typeof EnNesGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/nes': {
      id: '/en/nes'
      path: '/en/nes'
      fullPath: '/en/nes'
      preLoaderRoute: typeof EnNesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/n64-games': {
      id: '/en/n64-games'
      path: '/en/n64-games'
      fullPath: '/en/n64-games'
      preLoaderRoute: typeof EnN64GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/genesis-games': {
      id: '/en/genesis-games'
      path: '/en/genesis-games'
      fullPath: '/en/genesis-games'
      preLoaderRoute: typeof EnGenesisGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/gba-games': {
      id: '/en/gba-games'
      path: '/en/gba-games'
      fullPath: '/en/gba-games'
      preLoaderRoute: typeof EnGbaGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/gba': {
      id: '/en/gba'
      path: '/en/gba'
      fullPath: '/en/gba'
      preLoaderRoute: typeof EnGbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/arcade-games': {
      id: '/en/arcade-games'
      path: '/en/arcade-games'
      fullPath: '/en/arcade-games'
      preLoaderRoute: typeof EnArcadeGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/arcade': {
      id: '/en/arcade'
      path: '/en/arcade'
      fullPath: '/en/arcade'
      preLoaderRoute: typeof EnArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$blogId': {
      id: '/blog/$blogId'
      path: '/blog/$blogId'
      fullPath: '/blog/$blogId'
      preLoaderRoute: typeof BlogBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/how-to-play-games-online-without-downloading': {
      id: '/articles/how-to-play-games-online-without-downloading'
      path: '/articles/how-to-play-games-online-without-downloading'
      fullPath: '/articles/how-to-play-games-online-without-downloading'
      preLoaderRoute: typeof ArticlesHowToPlayGamesOnlineWithoutDownloadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleId': {
      id: '/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof ArticlesArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share-image': {
      id: '/api/share-image'
      path: '/api/share-image'
      fullPath: '/api/share-image'
      preLoaderRoute: typeof ApiShareImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/terms-of-service': {
      id: '/$locale/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/$locale/terms-of-service'
      preLoaderRoute: typeof LocaleTermsOfServiceRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/random': {
      id: '/$locale/random'
      path: '/random'
      fullPath: '/$locale/random'
      preLoaderRoute: typeof LocaleRandomRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy-policy': {
      id: '/$locale/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/$locale/privacy-policy'
      preLoaderRoute: typeof LocalePrivacyPolicyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/play-my-rom': {
      id: '/$locale/play-my-rom'
      path: '/play-my-rom'
      fullPath: '/$locale/play-my-rom'
      preLoaderRoute: typeof LocalePlayMyRomRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/live': {
      id: '/$locale/live'
      path: '/live'
      fullPath: '/$locale/live'
      preLoaderRoute: typeof LocaleLiveRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog': {
      id: '/$locale/blog'
      path: '/blog'
      fullPath: '/$locale/blog'
      preLoaderRoute: typeof LocaleBlogRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/library/genres/$genre': {
      id: '/library/genres/$genre'
      path: '/library/genres/$genre'
      fullPath: '/library/genres/$genre'
      preLoaderRoute: typeof LibraryGenresGenreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId/play': {
      id: '/games/$gameId/play'
      path: '/play'
      fullPath: '/games/$gameId/play'
      preLoaderRoute: typeof GamesGameIdPlayRouteImport
      parentRoute: typeof GamesGameIdRoute
    }
    '/$locale/games/$gameId': {
      id: '/$locale/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/$locale/games/$gameId'
      preLoaderRoute: typeof LocaleGamesGameIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/$blogId': {
      id: '/$locale/blog/$blogId'
      path: '/$blogId'
      fullPath: '/$locale/blog/$blogId'
      preLoaderRoute: typeof LocaleBlogBlogIdRouteImport
      parentRoute: typeof LocaleBlogRoute
    }
    '/embed/$locale/games/$gameId': {
      id: '/embed/$locale/games/$gameId'
      path: '/embed/$locale/games/$gameId'
      fullPath: '/embed/$locale/games/$gameId'
      preLoaderRoute: typeof EmbedLocaleGamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/games/$gameId/play': {
      id: '/$locale/games/$gameId/play'
      path: '/play'
      fullPath: '/$locale/games/$gameId/play'
      preLoaderRoute: typeof LocaleGamesGameIdPlayRouteImport
      parentRoute: typeof LocaleGamesGameIdRoute
    }
  }
}

interface LocaleBlogRouteChildren {
  LocaleBlogBlogIdRoute: typeof LocaleBlogBlogIdRoute
}

const LocaleBlogRouteChildren: LocaleBlogRouteChildren = {
  LocaleBlogBlogIdRoute: LocaleBlogBlogIdRoute,
}

const LocaleBlogRouteWithChildren = LocaleBlogRoute._addFileChildren(
  LocaleBlogRouteChildren,
)

interface LocaleGamesGameIdRouteChildren {
  LocaleGamesGameIdPlayRoute: typeof LocaleGamesGameIdPlayRoute
}

const LocaleGamesGameIdRouteChildren: LocaleGamesGameIdRouteChildren = {
  LocaleGamesGameIdPlayRoute: LocaleGamesGameIdPlayRoute,
}

const LocaleGamesGameIdRouteWithChildren =
  LocaleGamesGameIdRoute._addFileChildren(LocaleGamesGameIdRouteChildren)

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleBlogRoute: typeof LocaleBlogRouteWithChildren
  LocaleLiveRoute: typeof LocaleLiveRoute
  LocalePlayMyRomRoute: typeof LocalePlayMyRomRoute
  LocalePrivacyPolicyRoute: typeof LocalePrivacyPolicyRoute
  LocaleRandomRoute: typeof LocaleRandomRoute
  LocaleTermsOfServiceRoute: typeof LocaleTermsOfServiceRoute
  LocaleGamesGameIdRoute: typeof LocaleGamesGameIdRouteWithChildren
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleBlogRoute: LocaleBlogRouteWithChildren,
  LocaleLiveRoute: LocaleLiveRoute,
  LocalePlayMyRomRoute: LocalePlayMyRomRoute,
  LocalePrivacyPolicyRoute: LocalePrivacyPolicyRoute,
  LocaleRandomRoute: LocaleRandomRoute,
  LocaleTermsOfServiceRoute: LocaleTermsOfServiceRoute,
  LocaleGamesGameIdRoute: LocaleGamesGameIdRouteWithChildren,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface GamesGameIdRouteChildren {
  GamesGameIdPlayRoute: typeof GamesGameIdPlayRoute
}

const GamesGameIdRouteChildren: GamesGameIdRouteChildren = {
  GamesGameIdPlayRoute: GamesGameIdPlayRoute,
}

const GamesGameIdRouteWithChildren = GamesGameIdRoute._addFileChildren(
  GamesGameIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  ArcadeRoute: ArcadeRoute,
  ArcadeGamesRoute: ArcadeGamesRoute,
  BestUnblockedGamesRoute: BestUnblockedGamesRoute,
  FunQuizRoute: FunQuizRoute,
  FunQuizDothtmlRoute: FunQuizDothtmlRoute,
  GbaRoute: GbaRoute,
  GbaGamesRoute: GbaGamesRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  N64Route: N64Route,
  N64GamesRoute: N64GamesRoute,
  NesRoute: NesRoute,
  NesGamesRoute: NesGamesRoute,
  PlaystationGamesRoute: PlaystationGamesRoute,
  Ps1Route: Ps1Route,
  Ps1GamesRoute: Ps1GamesRoute,
  PuzzleGamesRoute: PuzzleGamesRoute,
  RacingGamesRoute: RacingGamesRoute,
  RandomRoute: RandomRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SegaGenesisRoute: SegaGenesisRoute,
  SegaGenesisGamesRoute: SegaGenesisGamesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SnesRoute: SnesRoute,
  SnesGamesRoute: SnesGamesRoute,
  SportsGamesRoute: SportsGamesRoute,
  TopIdleGamesRoute: TopIdleGamesRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiShareImageRoute: ApiShareImageRoute,
  ArticlesArticleIdRoute: ArticlesArticleIdRoute,
  ArticlesHowToPlayGamesOnlineWithoutDownloadingRoute:
    ArticlesHowToPlayGamesOnlineWithoutDownloadingRoute,
  BlogBlogIdRoute: BlogBlogIdRoute,
  EnArcadeRoute: EnArcadeRoute,
  EnArcadeGamesRoute: EnArcadeGamesRoute,
  EnGbaRoute: EnGbaRoute,
  EnGbaGamesRoute: EnGbaGamesRoute,
  EnGenesisGamesRoute: EnGenesisGamesRoute,
  EnN64GamesRoute: EnN64GamesRoute,
  EnNesRoute: EnNesRoute,
  EnNesGamesRoute: EnNesGamesRoute,
  EnPlaystationGamesRoute: EnPlaystationGamesRoute,
  EnPs1Route: EnPs1Route,
  EnPs1GamesRoute: EnPs1GamesRoute,
  EnSegaGenesisRoute: EnSegaGenesisRoute,
  EnSegaGenesisGamesRoute: EnSegaGenesisGamesRoute,
  EnSnesRoute: EnSnesRoute,
  EnSnesGamesRoute: EnSnesGamesRoute,
  GamesGameIdRoute: GamesGameIdRouteWithChildren,
  PlayGameIdRoute: PlayGameIdRoute,
  LibraryGenresGenreRoute: LibraryGenresGenreRoute,
  EmbedLocaleGamesGameIdRoute: EmbedLocaleGamesGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
